/**
 * 面试通关宝 - 题库数据文件
 * 你可直接编辑这个文件来更新所有内容！
 */

var QUESTIONS = [  { id: "self-intro-01", category: "自我介绍类", weight: "高", weightScore: 9, isPremium: false,
  question: "请做个自我介绍",
  interviewerWants: "考察表达逻辑、岗位匹配度。面试官不是想听你背简历，而是想快速判断你这个人靠不靠谱、适不适合这个岗位。",
  pitfallTips: "不要从头背到尾像念稿；不要超过2分钟没有重点；不要说和岗位无关的经历。核心：按「我是谁→我能做什么→我为什么适合」三段式走。",
  starFramework: { situation: "当前求职阶段或职业背景", task: "目标岗位的核心要求是什么", action: "我具备哪些匹配的技能和经验", result: "我能为团队带来什么价值" },
  versions: { short: "面试官好，我叫张明，有5年互联网运营经验，擅长通过A/B测试优化转化漏斗，过去一年将付费转化率从2.1%提升到3.8%。我来面试贵公司的用户增长负责人岗位，因为贵公司在知识付费领域的发展方向和我擅长的策略高度契合。", standard: "分三个方面。第一，职业背景。5年互联网运营经验，前3年在美团做商家运营，近2年专注用户增长。第二，核心能力。擅长数据驱动的精细化运营，去年通过6轮A/B测试将付费转化率从2.1%提升到3.8%，月增收280万。第三，来贵公司的原因。你们正从工具类产品向内容社区转型，这恰是我擅长的领域。" },
  compareExample: { poor: "我叫张明，今年27岁，毕业于XX大学市场营销专业。我平时喜欢打篮球。", excellent: "5年用户增长经验，核心能力是数据驱动的精细化运营——去年通过6轮A/B测试将付费转化率从2.1%提升到3.8%，月增收280万。我来面试这个岗位，因为贵公司正在从工具转型内容社区，这刚好是我最擅长的方向。", keyDiff: "普通回答是简历口述版，高分回答是价值推销版。" },
  migrationTips: "如果和目标岗位不完全匹配，提炼底层能力：运营的核心是理解用户+数据分析，思维框架跨行业通用。" },
  { id: "self-intro-02", category: "自我介绍类", weight: "中", weightScore: 6, isPremium: true,
  question: "用三个词形容你自己",
  interviewerWants: "考察自我认知能力和岗位匹配度。面试官想看的不是三个形容词本身，而是你给每个词配的证据。",
  pitfallTips: "不说大词不给证据；三个词不要雷同；不讲和工作无关的品质。每个词后面必须跟具体事例。",
  starFramework: { situation: "这个词对应的工作场景", task: "面临的挑战", action: "你展现这个品质的行为", result: "带来的结果" },
  versions: { short: "三个词：数据敏感、执行力强、善协作。数据敏感：发现周末订单取消率异常高，推动优化后取消率从15%降到3%。执行力强：3个月跑了6轮A/B测试，转化率提升80%。善协作：建立跨部门沟通机制被团队沿用至今。", standard: "数据敏感——在美团时发现周末午市订单取消率比平时高15%，追查后推动算法优化降到3%。结果导向——把转化率优化目标拆成12个小实验迭代完成。善于协作——建立跨部门对齐机制，项目交付速度提升40%。" },
  compareExample: { poor: "三个优点：勤奋、认真、好相处。", excellent: "三个词：数据敏感、结果导向、善于协作。每个词都配了故事和数据。", keyDiff: "普通回答给了大路词且无证据。高分回答每个词配了场景+结果的故事。" },
  migrationTips: "如果找不到和岗位直接相关的词，用可迁移能力来答。比如从销售转运营：沟通力强、数据分析、抗压。每个词的本质能力在新岗位上都能用。" },
  { id: "self-intro-03", category: "自我介绍类", question: "简历空白期在做什么", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察诚实度和自我管理能力。面试官真正担心的是这段空白期是否意味着能力断层或找不到工作。",
    pitfallTips: "不要撒谎或掩饰；不要表现出焦虑或愧疚；不要说「什么也没做」。核心策略：把空白期重新定义为充电期。",
    starFramework: { situation: "为什么有这段空白期", task: "我给自己设定的目标", action: "做了什么来保持学习和成长", result: "带给我的收获" },
    versions: { short: "3个月空窗期，我做了复盘+充电。系统复盘了过去3年项目经验，报数据分析课程拿了证书，旅行调整了状态。现在能力和状态都比之前更好。",
      standard: "我理解面试官关心这个问题。我有3个月的间隔期，这是我主动做的决定。我做了三件事：第一，系统复盘项目写成了方法论笔记。第二，系统学习了数据分析拿到证书。第三，旅行调整状态。现在我比离职前更有竞争力。" },
    migrationTips: "真正的gap原因不要撒谎，可以重新包装：被裁→团队业务调整。诚实但选择性表达，重点展示你学到了什么。" },
  { id: "self-intro-04", category: "自我介绍类", question: "你为什么频繁跳槽", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察稳定性和职业规划的清晰度。面试官担心：招你进来是不是干几个月又走？",
    pitfallTips: "不要抱怨前公司；不要说我成长太快了。核心：承认事实+每段离职逻辑一致+强调现在对稳定的认知转变。",
    starFramework: { situation: "为什么离开了那些公司", task: "希望在职业发展中获得什么", action: "做了哪些尝试", result: "学到了什么和对下一份工作的期望" },
    versions: { short: "前两年在职业探索期，每段帮我验证方向。第一段销售不适合，第二段确认数据分析是我擅长的事，第三段稳定工作2年。现在对要什么非常清晰，做好了长期深耕的准备。",
      standard: "坦诚说之前换得比较频繁，但背后有清晰逻辑线。第一份销售发现工作模式和自己性格不匹配。第二份市场推广发现缺数据支撑。第三份数据运营找到了对的感觉，做了2年。方向越来越清晰，停留时间越来越长。" },
    migrationTips: "如果确实因为个人原因离职，可以说：以前在团队协作方面不够成熟，后来学习了沟通课程，现在用更建设性的方式处理分歧。" },
  { id: "self-intro-05", category: "自我介绍类", question: "你对我们公司了解多少", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察求职动机真诚度和有没有做功课。面试官最怕听到「贵公司很好」却说不出好在哪。",
    pitfallTips: "不要只说贵公司很有名；不要只说公司不提岗位匹配。核心：展示你了解公司且想清楚了为什么是你和为什么是这家公司。",
    starFramework: { situation: "对贵公司业务的整体了解", task: "贵公司当前面临的核心挑战", action: "我的哪些经验可帮到你们", result: "加入后能产生的价值" },
    versions: { short: "做了系统研究。贵公司是AI驱动的SaaS公司，正处于从大客户向中小企业市场拓展的关键阶段。我的B端运营经验正好匹配——搭建的客户健康度评分系统将续费率从82%提升到91%。",
      standard: "分三个维度。第一，业务层面。贵公司是AI驱动的SaaS公司，今年发布了轻量化版本说明从大客户向中小市场拓展。第二，行业层面。SaaS核心指标是NDR，当前拓展中小企业市场对客户成功能力要求更高。第三，匹配度。我有3年B端客户运营经验，搭建的客户健康度模型将续费率从82%提升到91%。" },
    migrationTips: "如果跨行业，可以转化：贵公司面临的增长挑战和我之前行业的核心逻辑一样，运营的本质是理解用户+优化流程，思维框架可以跨行业通用。" },  { id: "resign-01", category: "离职原因类", question: "为什么离开上一家公司", weight: "高", weightScore: 9, isPremium: false,
    interviewerWants: "考察离职的成熟度和对前公司的评价方式。面试官真正关心的是：你离开了XX，会不会因为同样的原因离开我们？",
    pitfallTips: "不要说前公司坏话；不要说薪资太低；不要说过累。核心策略：用追求型语言代替逃离型语言。",
    starFramework: { situation: "上一家公司的发展阶段和我的职责", task: "对职业发展的期望", action: "做了哪些努力改变现状", result: "最终做出离开决定的原因" },
    versions: { short: "核心原因是成长天花板。我在那做了2年，公司进入平稳期后接触的挑战越来越少。和主管沟通过、申请过新项目后，发现内部空间有限。这是个理性决定。",
      standard: "离开不是因为负面原因。核心是成长天花板——公司进入稳定期后能接触的挑战增长有限。我主动和主管沟通过、申请过新项目、看了内部转岗，在确定内部难以解决后才看外部机会。" },
    migrationTips: "如果真实原因是钱少+加班多，包装成：我在上家公司积累了执行能力，现在希望在一个更大平台上发挥这些能力。" },
  { id: "resign-02", category: "离职原因类", question: "为什么被裁员", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察对待逆境的态度和诚实度。面试官关心的是：你是被优化掉的还是被无辜牵连的？",
    pitfallTips: "不要说谎；不要表现出受害者心态。核心：坦诚接受事实+理解公司决定+展示学到的经验。",
    starFramework: { situation: "公司业务调整背景", task: "团队面临的调整", action: "我在裁员前后的应对方式", result: "这段经历给我的新认知" },
    versions: { short: "创新业务部门被整体裁撤，公司战略收缩聚焦主业。理解也接受，这段经历让我学会在变化中主动调整。",
      standard: "所在的新业务探索部门做了8个月后被整体裁撤。原因是公司战略调整聚焦主业。公司给了N+1补偿和两个月缓冲期。这段经历让我学会在选公司时关注主业的可持续性。" },
    migrationTips: "如果因绩效被裁，可以说：当时某些能力没有达到要求，但这次经历是重要警醒，认真反思了短板并针对性提升。" },
  { id: "resign-03", category: "离职原因类", question: "从上一份工作中学到什么", weight: "中", weightScore: 4, isPremium: true,
    interviewerWants: "考察复盘能力和成长型思维。面试官想知道你是做了2年还是重复了2年。",
    pitfallTips: "不要说得太假；不要只夸前公司但你要走。核心：讲1-2个具体的认知升级时刻。",
    starFramework: { situation: "在上一家公司的一个具体项目", task: "当时面临的能力短板", action: "主动学习了什么或改变了什么", result: "能力提升对后续工作的影响" },
    versions: { short: "从执行者到owner的思维转变。以前等领导分配任务，后来主动思考自己发现问题解决问题。",
      standard: "最大收获是从执行者到owner的思维转变。第一年是优秀执行者。第二年负责客户续费率项目时，领导给了模糊目标。我主动分析数据发现规律，搭建健康度模型，最终挽回12个高危客户。从那以后我做任何事前先问自己：这件事的本质是什么？" },
    migrationTips: "如果上份工作确实简单重复，可以说：这反而给了我观察窗口，理解了持续成长的重要性。" },
  { id: "resign-04", category: "离职原因类", question: "如果老板加薪会留下吗", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察离职的根本原因是不是钱。面试官想知道你是不是拿这个offer去抬价。",
    pitfallTips: "不要说会考虑。核心：坦诚表达离职核心原因不是钱，而是成长/方向/平台。",
    starFramework: { situation: "正在面试这家公司的原因", task: "选择职业的核心标准", action: "加薪能覆盖哪些", result: "为什么加薪不能解决根本问题" },
    versions: { short: "不会。加薪只能解决报酬问题不能解决成长问题。我离职的核心驱动力是成长空间。",
      standard: "不会。如果只是钱的问题，我会和老板谈而不是坐在这里。加薪解决的是报酬公平感，不是职业发展。我看中贵公司是因为有机会接触更复杂的业务和更大的挑战。" },
    migrationTips: "如果真实原因包括薪资，可以说：薪资是我考虑的因素之一，但我面试贵公司的第一驱动力是看好平台方向。" },
  { id: "resign-05", category: "离职原因类", question: "有没有同时面试其他公司", weight: "中", weightScore: 4, isPremium: true,
    interviewerWants: "考察面试诚意和竞争压力。面试官想知道你是只投了一家还是同时在看很多。",
    pitfallTips: "不要只说看了贵公司一家；不要说很多家公司的名字。核心：诚实承认+强调贵公司是优先选择。",
    starFramework: { situation: "我的求职策略", task: "筛选公司的标准", action: "贵公司在这几项上的得分", result: "贵公司是优先选择" },
    versions: { short: "同时在看几家，但贵公司是最优先选择。我做了一个偏好矩阵比较，贵公司综合评分最高。",
      standard: "诚实说在看好几家。我不是海投——筛选了20家只投了5家。贵公司是我最用心准备且综合评分最高的。所以拿到offer大概率会接。" },
    migrationTips: "如果只面了一家，可以说：目前只面了贵公司一家，因为筛选后贵公司排第一顺位。" },  { id: "career-01", category: "职业规划类", question: "未来3-5年职业规划", weight: "高", weightScore: 7, isPremium: false,
    interviewerWants: "考察自我认知清晰度和这个岗位在你规划中的位置。面试官担心你是不是拿这个岗位当跳板。",
    pitfallTips: "不要说我三年当总监；不要说我跟着公司成长。核心：让面试官觉得这个岗位是你规划中的关键步骤。",
    starFramework: { situation: "目前处于职业生涯的哪个阶段", task: "对下一个阶段的目标设定", action: "计划通过什么路径实现目标", result: "3-5年后成为什么样的人" },
    versions: { short: "1-2年深耕成为团队最懂业务的人，3-5年拓展从执行者成长为策略制定者。选贵公司因为你们提供完整的成长路径。",
      standard: "分两个阶段。1-2年完成融入——前3个月快速上手，前半年出项目成果，第一年独立承担重要模块。3-5年完成升级——在专业上成为客户成功专家，在视野上能理解跨部门联动关系。" },
    migrationTips: "如果没想好，可以说：对3-5年保持开放心态，但对下一份工作有清晰标准——找一个能持续成长的平台。" },
  { id: "career-02", category: "职业规划类", question: "为什么选择这个行业", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察行业理解深度和求职动机的真诚度。面试官想知道你是真心喜欢还是恰好在找工作。",
    pitfallTips: "不要说这个行业有前景——太浅。核心：讲清楚选择背后的价值判断逻辑。",
    starFramework: { situation: "对行业的接触和认知", task: "基于什么标准做出的选择", action: "为进入这个行业做了什么准备", result: "这个选择带来的结果" },
    versions: { short: "做了三层面验证。行业层面SaaS是复利型商业模式，岗位层面客户成功需要关系+策略的能力组合，个人层面亲身体验后更加确信。",
      standard: "先是感性兴趣——发现那些有专属客户成功经理的SaaS产品续费率和满意度更高。再是理性验证——系统读《SaaS创业路线图》和行业分析。最后确定了SaaS在中国快速增长、客户成功是核心环节、需要的能力正好是我强项。" },
    migrationTips: "如果从完全不同的行业转过来，先说跨行业的事实，再展示学习决心和可迁移能力。" },
  { id: "career-03", category: "职业规划类", question: "入职后怎么开展工作", weight: "高", weightScore: 8, isPremium: false,
    interviewerWants: "考察思考结构和执行力。面试官想知道你来这儿不是被动的，你有自己的想法。",
    pitfallTips: "不要听领导安排——太被动；不要给太宏大计划——不切实际。核心：展示前90天行动方案。",
    starFramework: { situation: "入职后的状态和目标", task: "分阶段要达成的里程碑", action: "每个阶段的具体行动计划", result: "希望在什么时候出什么成果" },
    versions: { short: "前90天行动计划。第一个月快速融入，第二个月开始产出跑通闭环，第三个月主动发现提出优化建议。",
      standard: "第一个30天快速融入——和每人做1on1、体验产品全流程、跟听客户沟通。第二个30天开始产出——选一个项目跑通从理解到执行的全流程。第三个30天主动发现——基于观察提出业务优化建议。" },
    migrationTips: "如果换行业，在前90天计划中突出学习能力部分，诚实展示学习计划反而让人放心。" },
  { id: "career-04", category: "职业规划类", question: "什么时候开始找工作的", weight: "中", weightScore: 4, isPremium: true,
    interviewerWants: "考察离职/求职时机是否合理。是你规划好的还是有压力的被动反应。",
    pitfallTips: "不要说刚离职急着找。核心：把求职时间点和职业节奏关联起来。",
    starFramework: { situation: "近期职业状态回顾", task: "为什么这个时间点适合看机会", action: "做了什么准备", result: "这个时间点的判断" },
    versions: { short: "上个月开始。在岗位做了1年8个月发现学习曲线变平，先确认了内部没有发展空间后才开始看机会。",
      standard: "大约一个月前开始。做满1年半时做了自评，发现一段时间没有能力突破。但没有马上离职——先跟主管聊了发展路径、主动做了新项目验证、看了外部岗位评估竞争力。确认时机到了才行动。" },
    migrationTips: "如果是刚被裁员，可以说：既然机会来了，把时间点当作重新规划方向的机会。" },
  { id: "career-05", category: "职业规划类", question: "希望从下一份工作获得什么", weight: "中", weightScore: 6, isPremium: true,
    interviewerWants: "考察求职动机是否清晰以及这份工作能否满足你的期望。如果给不了你也会走。",
    pitfallTips: "不要只说薪资福利；不要说没什么特别想要的；不要说了一个这家公司给不了的。核心：说2-3个具体期望+论证这家公司能满足。",
    starFramework: { situation: "对当前职业阶段的认识", task: "对下一份工作的关键诉求", action: "为什么贵公司能满足这些诉求", result: "加入后的预期贡献" },
    versions: { short: "三个层次。底层成长空间，中层价值感，顶层团队氛围。贵公司都能满足。",
      standard: "三个层次。底层必须满足成长空间——我看工作第一标准是能否变强。中层重要价值感——客户成功有反馈闭环能看见影响。顶层加分团队氛围——面试中感受到务实和直接。" },
    migrationTips: "如果更看重薪资，可以包装：薪资当然重要，但不会为几千块钱去不能成长的公司。" },  { id: "weakness-01", category: "优缺点类", question: "你的最大缺点是什么", weight: "高", weightScore: 8, isPremium: false,
    interviewerWants: "考察自我认知的诚实度和改进意愿。面试官想看你是否能客观看待自己。",
    pitfallTips: "不要说假缺点（我太完美主义了）；不要说致命缺点。核心：选一个真实、不致命、且你在改进的缺点。",
    starFramework: { situation: "这个缺点的具体表现场景", task: "认识到缺点对工作的影响", action: "采取了什么具体措施改进", result: "改进效果和持续的自我管理" },
    versions: { short: "有时候过于关注细节影响效率。后来用二八原则和初稿截止线来管理，先在快和好之间找平衡。",
      standard: "有时过于关注细节影响效率。之前做竞品分析报告在图表美观上花很多时间，结果被问到核心问题答不好。后来给每个任务设时间预算，先做到60分再优化，从完美变成完成加迭代。" },
    migrationTips: "选缺点时避开和岗位核心要求冲突的。面容户成功不说不喜欢沟通，面数据分析不说数学不好。" },
  { id: "weakness-02", category: "优缺点类", question: "收到过最有价值的批评", weight: "中", weightScore: 4, isPremium: true,
    interviewerWants: "考察接受反馈的能力和自我改进意愿。面试官想确认你能听进去批评。",
    pitfallTips: "不要说没收到过批评；不要说太轻的批评。核心：选真实有刺痛感的批评，重点讲听后做了什么改变。",
    starFramework: { situation: "什么时候谁对你说了什么批评", task: "当时的第一反应", action: "做了什么来改进", result: "改变后的效果" },
    versions: { short: "主管说「你总想等数据完美再出方案，但业务不等你」。后来改成先出60分版本再迭代的方式。",
      standard: "主管说「你总想等数据完美再出方案，但业务不等你」。后来我设了行动截止线、用MVP思维先做简单版本验证、做计划时先问自己明天必须交能交什么。后续项目启动快了近一倍。" },
    migrationTips: "如果很少被批评，可以说一个自我批评的认知触发。" },
  { id: "weakness-03", category: "优缺点类", question: "核心竞争力是什么", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察自我认知和岗位匹配度。面试官想知道你的优点对这个岗位有没有用。",
    pitfallTips: "不要只说了不给证据；不要说和岗位无关的优点。核心：选2个和岗位最相关的优点配数据案例。",
    starFramework: { situation: "工作中体现这个优点的场景", task: "这个优点如何帮你完成挑战", action: "做了什么来发挥这个优势", result: "带来的量化成果" },
    versions: { short: "在资源有限的情况下找到增长杠杆。预算只有同行1/10时通过分析数据把精力转向留存，将7日留存从30%提升到58%。",
      standard: "在资源有限的情况下找到增长杠杆。预算只有同行1/10的情况下，我发现拉新ROI不如留存划算。于是改变策略将60%精力转向留存，设计自动化新用户成长体系，将7日留存从30%提升到58%。" },
    migrationTips: "如果没有特别亮眼的优势数据，找一个相对突出的点包装学习速度或执行力。" },
  { id: "weakness-04", category: "优缺点类", question: "有没有系统学习克服短板的经历", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察学习力和自驱力。面试官想看你是被动成长还是主动成长的人。",
    pitfallTips: "不要说了没有结果的学习；不要说得太大而全。核心：具体场景+明确问题+学习路径+结果验证。",
    starFramework: { situation: "发现了自己在什么方面不足", task: "这个问题对工作的影响", action: "制定了什么学习计划并执行", result: "能力提升后带来的工作变化" },
    versions: { short: "发现数据分析是短板，制定3个月攻坚计划。从学SQL到用公开数据实操练手再到实战项目，最终将复购率提升15%。",
      standard: "做运营决策时靠经验被老板问住，决心系统性学习数据分析。第1个月学SQL课程，第2个月用公开数据练手，第3个月在工作中实战。最终帮团队将用户复购率提升15%。" },
    migrationTips: "如果确实没有系统学习经历，可以说一个正在进行的：最近发现XX需要提升，已经报名了XX课程。" },
  { id: "weakness-05", category: "优缺点类", question: "这个岗位最需要的能力你具备吗", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察对岗位的理解深度和自我匹配度。面试官想知道你是否真的了解这个岗位要什么样的人。",
    pitfallTips: "不要直接复制JD上的要求；不要所有要求都说满足。核心：说核心的2-3个要求，每个配自己的案例。",
    starFramework: { situation: "对这个岗位的核心理解", task: "排在前3位的关键能力", action: "每个能力对应的证据", result: "匹配度总评" },
    versions: { short: "三个核心能力：数据分析（有健康度评分模型成果）、跨部门沟通（协作效率提升40%）、抗压（有标准化处理机制）。匹配度打8分。",
      standard: "第一层硬能力数据分析——搭建了健康度评分模型用12个指标预警流失。第二层软能力跨部门沟通——做需求翻译者帮客户把需求转成产品语言。第三层心力抗压——有标准化处理80%问题的机制。匹配度打8分，差2分在行业深度但3个月能补上。" },
    migrationTips: "如果能力确实有差距，坦诚说：我分析了JD，XX和XX能力我具备但XX还需补强，制定了XX计划。" },
  { id: "project-01", category: "项目经验类", question: "讲一个最有成就感的项目", weight: "高", weightScore: 9, isPremium: true,
    interviewerWants: "考察项目复杂度、你的具体贡献、解决问题的能力。面试官想判断你做成的难度大不大、角色是执行者还是推动者。",
    pitfallTips: "不要说太简单的项目；不要用我们代替我；不要只有背景没有结果。核心：选有挑战、有行动、有数据的项目。",
    starFramework: { situation: "在公司负责什么模块或项目", task: "面对XX挑战需要在XX时间内达成XX目标", action: "做了三件事：诊断、方案设计、推动执行", result: "最终达成了XX结果数据为XX" },
    versions: { short: "客户续费率提升项目。通过数据诊断发现80%流失客户功能使用不足3个，搭建12维度健康度评分模型，推动跟进后续费率从82%提升到91%。",
      standard: "客户续费率提升项目。当时年续费率82%低于行业平均。我分三步推进：第一步分析所有流失客户数据发现80%流失客户功能使用不足3个。第二步搭建12维度健康度评分模型每周自动跑数据预警。第三步推动客户成功团队分层跟进。最终续费率从82%到91%。" },
    migrationTips: "如果项目不够亮眼，重点展示你的思考和推动过程，而不只是结果。" },
  { id: "project-02", category: "项目经验类", question: "讲讲你遇到的最难解决的问题", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察问题解决能力和韧性。面试官想知道你面对真正的困难时是怎么思考和行动的。",
    pitfallTips: "不要说太简单的问题；不要只说困难不说解法。核心：讲清楚难点在哪、你做了什么、最后怎样。",
    starFramework: { situation: "问题发生的背景和挑战", task: "需要达成的目标", action: "你的分析和解决方案", result: "最终的结果和经验" },
    versions: { short: "预算只有同行1/10却要做同样增长指标。通过分析数据发现留存率比拉新更划算，改变策略将留存从30%提升到58%。",
      standard: "创业公司时预算只有大公司1/10但要做同样增长。分析后发现投信息流广告越投越亏。改变思路转向留存，设计自动化新用户成长体系，用行为数据识别用户卡在哪并针对性干预。最终将留存从30%提升到58%。" },
    migrationTips: "如果没有特别难的经历，可以说一个工作中的小困难但重点展示思考过程。" },
  { id: "project-03", category: "项目经验类", question: "你怎么面对项目中的压力", weight: "高", weightScore: 7, isPremium: true,
    interviewerWants: "考察抗压能力和情绪管理。面试官想知道你在压力下是崩溃还是沉着应对。",
    pitfallTips: "不要说我不怕压力；不要只说压力不说应对方法。核心：展示你在压力下的思考方式和行动。",
    starFramework: { situation: "什么场景下遇到了压力", task: "压力和挑战的具体表现", action: "你是怎么应对的", result: "最终的结果" },
    versions: { short: "项目上线前发现数据口径有问题可能影响效果。主动加班两天重新核算，和团队坦诚沟通后调整方案，最终效果达标。",
      standard: "项目上线前发现数据口径有问题。当时压力很大因为时间紧任务重。我做了三件事：第一冷静分析问题边界——搞清楚影响有多大。第二和团队坦诚沟通——不隐瞒问题。第三加班重新核算并调整方案。最终效果达标团队关系也没有受到影响。" },
    migrationTips: "如果没遇到过大压力，可以说日常工作中的时间管理压力。" },
  { id: "project-04", category: "项目经验类", question: "你怎么协调跨部门资源", weight: "中", weightScore: 6, isPremium: true,
    interviewerWants: "考察协作能力和推动力。面试官想知道你在没有管理权的情况下怎么把事情做成。",
    pitfallTips: "不要抱怨其他部门不配合；不要说自己一个人搞定一切。核心：展示你如何通过沟通和机制来推动。",
    starFramework: { situation: "需要跨部门协作的项目", task: "需要协调哪些部门", action: "用了什么方法和机制", result: "协作的效果" },
    versions: { short: "建立跨部门对齐机制：月初确认各方排期和需求、共享数据看板让大家看到进展、每周15分钟站会同步。项目交付速度提升40%。",
      standard: "增长工作需要协调产品技术内容多个部门。我建立了一套机制：每月初和各部对齐目标和排期、建立共享数据看板让进展透明、每周15分钟站会只问做了什么和需要什么帮助。这套机制让项目交付速度提升40%。" },
    migrationTips: "如果没有跨部门协作经验，可以说在团队内推动共识的经历。" },
  { id: "project-05", category: "项目经验类", question: "如果重做这个项目会怎么改进", weight: "中", weightScore: 6, isPremium: true,
    interviewerWants: "考察复盘能力和反思深度。面试官想知道你做完了有没有真的思考过哪里可以更好。",
    pitfallTips: "不要说我觉得做得挺好的没什么要改的。核心：挑1-2个具体的改进点+能产生可量化的改善。",
    starFramework: { situation: "当初做这个项目的背景和方案", task: "项目做完后回头的反思", action: "如果再让我做会在哪些环节不同", result: "预期能带来的效果提升" },
    versions: { short: "会提前预警窗口，从行为数据追踪升级到态度数据追踪。另外做客户分层建模，不同体量客户用不同评分标准。",
      standard: "如果重做客户续费率项目，会在三方面改进。第一预警窗口太晚——行为数据报警时客户已动摇4周，应加NPS脉冲调查提前预警。第二缺客户分层建模——大小客户行为模式不同应分不同评分标准。第三干预手段太单一——做客户沟通偏好调研，不同偏好用不同策略。" },
    migrationTips: "如果项目本身很成功，可以说虽然成功了但仍有可以优化的空间。" },
  { id: "project-06", category: "项目经验类", question: "讲一个失败的案例", weight: "高", weightScore: 7, isPremium: true,
    interviewerWants: "考察如何看待失败和从失败中学习的能力。面试官想看的不是你有没有失败过，而是你面对失败的态度。",
    pitfallTips: "不要说我没有失败的案例；不要把失败归咎于外部。核心：选真实有责任的失败+展示反思+学到的东西。",
    starFramework: { situation: "失败项目发生的背景", task: "当时的目标和策略", action: "哪里出了问题", result: "学到了什么以及后来怎么应用" },
    versions: { short: "推荐有礼活动ROI预估1:3实际只有1:0.8。复盘发现激励设计有问题、分享流程太长、没有做小规模测试。这次教会我在增长活动前先用最小实验验证核心假设。",
      standard: "推荐的用户增长活动ROI预估1:3实际只有1:0.8。复盘发现激励对用户吸引力不足、分享流程有5步每一步都在流失、没有做小规模验证就全量上线。这次教会我：任何增长活动前先用最小实验验证核心假设再投入资源。" },
    migrationTips: "如果确实没有失败经历，可以说一个做得不够好但没算失败的项目。" },  { id: "stress-01", category: "压力面试类", question: "我为什么要录用你", weight: "高", weightScore: 9, isPremium: true,
    interviewerWants: "考察自信度和说服力。面试官想看你能否在压力下清晰地总结自己的价值。",
    pitfallTips: "不要说没有我也行的谦虚话；不要只说空话。核心：用三个最有说服力的理由+证据。",
    starFramework: { situation: "这个岗位最需要什么", task: "我凭什么适合", action: "三个匹配的证据", result: "录用我带来的价值" },
    versions: { short: "三个理由。第一有直接相关经验——做过客户续费率优化项目。第二同时具备数据分析和跨部门推动能力。第三对贵公司做了深入研究且意愿度很高。",
      standard: "三个理由。第一经验匹配——我做的客户续费率优化和这个岗位的要求高度一致。第二能力组合——数据分析+跨部门推动，能发现问题也能解决问题。第三意愿度——我花了大量时间研究贵公司，不是海投。" },
    migrationTips: "如果经验不完全匹配，强调学习能力和可迁移技能。" },
  { id: "stress-02", category: "压力面试类", question: "你的学历不太够", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察抗压能力和对学历的态度。面试官在测试你在被挑战时的反应。",
    pitfallTips: "不要愤怒反驳；不要表现出自卑。核心：自信地展示学历之外的能力证明。",
    starFramework: { situation: "学历背景的实际情况", task: "面试官对学历的担忧", action: "用什么实际成果证明了能力", result: "能力远大于学历" },
    versions: { short: "学历不代表学习能力。毕业后我拿下了Google数据分析证书、自学SQL和Tableau。工作中实际产出证明了能力——续费率提升9%就是最好说明。",
      standard: "学历不代表学习能力也代表不了工作能力。毕业后4年我拿下了数据分析证书、在工作中做出了实际成果——续费率提升9%保住了300万合同额。华为任正非说过文凭只是敲门砖真正的能力是在工作中练出来的。" },
    migrationTips: "如果学历确实偏低，坦诚面对并用实际成果说话就是最好的回应。" },
  { id: "stress-03", category: "压力面试类", question: "你没有这个行业经验", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察转行适应能力和学习能力。面试官在测试你的信心和应对策略。",
    pitfallTips: "不要回避问题；不要说虽然没经验但我很努力。核心：展示可迁移能力和学习准备。",
    starFramework: { situation: "跨行业的背景", task: "行业经验的差距", action: "已有的可迁移能力和学习计划", result: "快速上手的能力证明" },
    versions: { short: "虽然行业不同但运营的核心能力通用。过去积累的用户分层和转化优化方法论完全可以迁移。我已经花时间系统学习了这个行业的知识。",
      standard: "行业经验可以通过学习快速补充但底层能力是多年积累的。我在过去行业积累的用户分层数据分析和转化优化方法论跨行业完全适用。我已经系统学习了贵公司相关的行业知识包括竞品分析。" },
    migrationTips: "提前做好功课展示你对新行业的了解程度。" },
  { id: "stress-04", category: "压力面试类", question: "你年纪太大了/太小了", weight: "中", weightScore: 6, isPremium: true,
    interviewerWants: "考察自信度和心理素质。面试官在测试你面对偏见时的反应。",
    pitfallTips: "不要激动反驳；不要表现出不自信。核心：把关注点从年龄转移到能力和价值。",
    starFramework: { situation: "年龄与岗位的实际情况", task: "面试官对年龄的顾虑", action: "用实际能力证明年龄不是问题", result: "年龄带来的是优势而非劣势" },
    versions: { short: "年龄不是能力的衡量标准。我的优势是经验积累让我对领域有深入理解，同时保持了很强的学习意愿和能力。",
      standard: "年龄不应该成为评判标准。我虽然年轻但已经用实际项目证明了自己能做出成绩。同时年轻人意味着精力充沛学习速度快愿意接受新事物。这些恰恰是这个岗位需要的特质。" },
    migrationTips: "把年龄转化为优势：年长=经验丰富，年轻=学习快有冲劲。" },
  { id: "stress-05", category: "压力面试类", question: "你的薪资要求太高了", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察薪资谈判的灵活性和逻辑性。面试官想看你是否能理性地评估自己的价值。",
    pitfallTips: "不要立刻降价；不要僵持不让步。核心：展示有理有据的价值逻辑和有弹性的谈判态度。",
    starFramework: { situation: "薪资预期的依据", task: "面试官对薪资的顾虑", action: "基于市场数据和能力产出给出合理范围", result: "双方都能接受的方案" },
    versions: { short: "薪资预期基于市场行情和能力评估。当然我会看整体方案而不是只盯数字，如果发展空间好也可以调整。",
      standard: "薪资预期是基于三个依据：行业薪酬报告、过去一年的实际产出、这个岗位的职责复杂度。当然薪资只是考量因素之一，如果公司有清晰的成长路径和调薪机制我可以灵活调整。" },
    migrationTips: "提前做好行业薪资调研，给出有依据的范围不是拍脑袋要价。" },
  { id: "salary-01", category: "薪资谈判类", question: "你期望的薪资是多少", weight: "高", weightScore: 9, isPremium: true,
    interviewerWants: "考察薪资预期的合理性。面试官想知道你要的价在不在预算内。",
    pitfallTips: "不要只报月薪不提总包；不要要价太离谱。核心：提前做好功课给出合理范围。",
    starFramework: { situation: "目前薪资构成", task: "跳槽的合理涨幅预期", action: "基于什么数据得出这个预期", result: "期望的薪资范围" },
    versions: { short: "基于行业薪酬报告和我的项目成果期望在XX-XX之间。也愿意了解贵公司的薪资结构和福利体系综合评估。",
      standard: "基于行业数据显示我这个级别的市场区间、我过去一年的项目产出价值、这个岗位的职责复杂度，我认为合理范围是XX-XX。也愿意了解贵公司的整体薪酬方案。" },
    migrationTips: "如果不清楚行业薪资水平，坦诚问HR先分享范围再谈。" },
  { id: "salary-02", category: "薪资谈判类", question: "如果薪资达不到预期怎么办", weight: "高", weightScore: 8, isPremium: true,
    interviewerWants: "考察候选人的灵活性和真实动机。HR想试探你是来谈钱的还是来做事的。",
    pitfallTips: "不要说不来；不要说来多少都来。核心：展示你在薪资外也在意其他东西。",
    starFramework: { situation: "评估一份工作的标准体系", task: "薪资在其中的权重", action: "如果薪资有差距如何评估整体方案", result: "灵活的处理方式" },
    versions: { short: "如果差距在10%以内会看整体方案。如果差距较大愿意聊聊差距的原因以及有没有其他补偿方案。",
      standard: "分情况。如果差距在10%以内我会看整体方案——成长空间调薪机制期权等综合起来有没有诚意。如果差距大我愿意和公司聊聊差距的原因是我展示的价值不够还是公司薪资体系的问题。" },
    migrationTips: "如果有底线，诚实表达但留出谈判空间。" },
  { id: "salary-03", category: "薪资谈判类", question: "你目前的薪资结构", weight: "高", weightScore: 9, isPremium: true,
    interviewerWants: "考察诚实度和跳槽的真实动机。面试官通过你的薪资判断你的级别和期望。",
    pitfallTips: "不要虚报薪资；不要只说月薪不提总包。核心：清晰报出总包+合理涨幅。",
    starFramework: { situation: "目前薪资构成包括哪些", task: "对跳槽的合理涨幅预期", action: "基于什么数据得出这个预期", result: "期望的薪资范围" },
    versions: { short: "目前月薪XX万全年总包约XX万。期望有XX的涨幅。基于行业数据和我过去一年的产出这个预期是合理的。",
      standard: "目前总包约XX万包括月薪和年终奖。基于行业数据和我的能力评估期望有XX涨幅达到XX万。这个预期是合理的当然也愿意看整体方案。" },
    migrationTips: "先问清楚贵公司的薪资结构再报价，让HR先出牌。" },
  { id: "salary-04", category: "薪资谈判类", question: "除了薪资还看重什么", weight: "中", weightScore: 4, isPremium: true,
    interviewerWants: "考察求职动机的多元性和匹配度。面试官想判断如果薪资给不到还有什么可以弥补。",
    pitfallTips: "不要没啥特别看重的。核心：给出薪资之外的考量因素每个说清楚为什么重要。",
    starFramework: { situation: "对下一份工作的期待", task: "除了薪资还关注哪些维度", action: "为什么这些维度重要", result: "这些因素和贵公司的匹配度" },
    versions: { short: "成长空间第一、团队文化第二、业务方向第三。这三点贵公司都让我感到匹配。",
      standard: "薪资之外看重成长空间——希望加入有明确成长路径的平台。团队氛围——和什么样的人一起工作很重要。业务方向——做自己认同的事才有持续动力。这三方面贵公司都很匹配。" },
    migrationTips: "如果最看重薪资，把薪资嵌在成长的前提下来表达。" },
  { id: "salary-05", category: "薪资谈判类", question: "你还有什么想问我们的", weight: "低", weightScore: 3, isPremium: true,
    interviewerWants: "考察主动性和思考深度。很多候选人输在这个问题不是说不好而是没问题。",
    pitfallTips: "不要没有问题；不要问福利怎么样太浅。核心：准备3个高质量问题展示思考深度。",
    starFramework: { situation: "基于面试交流和公司研究", task: "提出能展示思考深度的问题", action: "不同角色问不同类型的问题", result: "通过提问加深理解和展示自己" },
    versions: { short: "三个问题。第一前3个月成功的标准是什么。第二团队目前最大的挑战是什么。第三这个岗位上优秀的人具备什么特质。",
      standard: "三个问题。第一前3个月成功的标准是什么——这个帮我对齐期望。第二团队目前最大的挑战是什么——进来后知道往哪使劲。第三这个岗位上优秀的人具备什么特质——了解优秀的标准。" },
    migrationTips: "至少准备3个问题，无论什么岗位都可以问成功标准那个问题。" },  { id: "team-01", category: "团队协作类", question: "和同事发生冲突怎么处理", weight: "中", weightScore: 6, isPremium: true,
    interviewerWants: "考察冲突处理能力和情商。面试官想知道你是对抗逃避还是能建设性解决。",
    pitfallTips: "不要说我不和人冲突——不真实；不要说我直接怼回去——不成熟。核心：展示冷静倾听和聚焦事不聚焦人。",
    starFramework: { situation: "冲突发生的场景", task: "矛盾的核心分歧", action: "如何引导双方沟通", result: "冲突解决后团队的变化" },
    versions: { short: "先冷静再分别倾听双方视角，不站队不评判。然后把焦点从谁对谁错转到哪种方案对项目更好。最终转化为建设性讨论。",
      standard: "先给双方冷静时间不要在情绪上硬讲道理。然后分别找两位同事独立倾听了解各自视角不表态不评判。最后拉到一起从项目最好的结果出发讨论而不是谁对谁错。这种处理方式让我解决过团队内部的严重矛盾。" },
    migrationTips: "如果没处理过冲突可以说作为旁观者的观察和学习。" },
  { id: "team-02", category: "团队协作类", question: "如何推动跨部门合作", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察协作能力和推动力。面试官想知道你在没有汇报关系时怎么把事做成。",
    pitfallTips: "不要抱怨其他部门不配合。核心：展示你如何通过机制和沟通来推动而非靠关系或权力。",
    starFramework: { situation: "需要跨部门合作的项目", task: "实现合作的关键障碍", action: "建立了什么协作机制", result: "合作的效果" },
    versions: { short: "提前对齐共同目标，建立共享进度看板，定期同步会议。出了问题不争责任先推进解决，事后复盘流程优化。",
      standard: "跨部门合作的最大障碍是目标不一致。我的做法是项目启动前先和各方对齐共同目标，建立共享进度看板让信息透明，每周15分钟站会同步进展。出了问题不纠缠责任先解决问题再复盘流程。" },
    migrationTips: "如果经验不足，可以说出一个原则并展示学习意愿。" },
  { id: "team-03", category: "团队协作类", question: "你对远程办公怎么看", weight: "低", weightScore: 3, isPremium: true,
    interviewerWants: "考察对工作模式的适应性和边界感。",
    pitfallTips: "不要说我完全接受远程；不要说我必须去办公室。核心：展示你对结果导向的理解。",
    starFramework: { situation: "对远程办公的态度", task: "远程办公的挑战", action: "如何克服这些挑战", result: "远程办公的效果" },
    versions: { short: "接受混合办公模式，关键是结果导向而非工时导向。有成熟的远程协作经验和工作方法。",
      standard: "远程办公的优势是灵活高效短板是沟通成本高。核心是要结果导向而不是工时导向。我有成熟的远程协作经验包括每日站会、周报同步、即时通讯工具的高效使用。" },
    migrationTips: "无论持什么态度，展示你适应不同工作模式的灵活性。" },
  { id: "team-04", category: "团队协作类", question: "怎么看待跨部门推诿", weight: "中", weightScore: 6, isPremium: true,
    interviewerWants: "考察你在复杂协作中的成熟度。面试官想知道你是抱怨的人还是解决问题的人。",
    pitfallTips: "不要开始抱怨其他部门不好。核心：承认问题的存在+展示你的应对方法+重点在往前推进。",
    starFramework: { situation: "遇到跨部门推诿的具体场景", task: "这个场景下的核心问题", action: "如何往前推动的", result: "结果和方法论沉淀" },
    versions: { short: "推诿根源是目标不一致和边界不清晰。我的策略三层：事前对齐、事中不争责任先推进、事后复盘流程优化。",
      standard: "推诿的根源不是人的问题而是目标不统一和责任边界模糊。我在项目启动前先牵头对齐目标和边界。如果推诿已发生不纠缠责任先推进解决。事后推动流程优化从根上减少未来推诿。" },
    migrationTips: "如果没有特别好的案例，先摆出原则再展示积累经验。" },
  { id: "team-05", category: "团队协作类", question: "习惯在什么样的团队工作", weight: "低", weightScore: 3, isPremium: true,
    interviewerWants: "考察文化匹配度。面试官想确认你的工作方式和团队文化是否兼容。",
    pitfallTips: "不要都说行等于没回答。核心：先说自己看重的特质再和面试感受呼应。",
    starFramework: { situation: "最有帮助的团队特质", task: "好的团队文化对工作成果的影响", action: "如何为这种文化做贡献", result: "在这种团队中发挥最好" },
    versions: { short: "心理安全+信息透明+成长导向的团队。大家敢说真话、没有信息壁垒、每个人都在进步。",
      standard: "心理安全的团队——大家敢说真话承认错误。信息透明的团队——目标进度困难都公开。成长导向的团队——每做完一件事都在变强。和贵公司团队接触下来感觉很匹配。" },
    migrationTips: "展示适应性的同时也不要有太高的门槛。" },
  { id: "leader-01", category: "领导力类", question: "你如何带团队", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察管理风格和管理思维。面试官想知道你对管理的理解是权力还是责任。",
    pitfallTips: "不要管理就是管人这么片面。核心：好管理=帮团队拿结果+帮成员成长。",
    starFramework: { situation: "带团队的经验", task: "管理中的挑战", action: "你的管理方法", result: "团队的变化" },
    versions: { short: "做三件事：定方向告诉团队我们去哪、清障碍把阻挡前进的问题解决掉、给反馈让每个人知道自己做得好不好。",
      standard: "管事——目标分解进度跟进是基础。带人——发现每个人优势帮他们成长。建体系——建立可持续运转的流程让团队在没有盯着时也能高效运转。好管理者不是自己多厉害而是团队多厉害。" },
    migrationTips: "如果没带过团队，可以说带实习生或项目的管理经验。" },
  { id: "leader-02", category: "领导力类", question: "如何给下属分配任务", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察因材施教的管理能力。面试官想知道你会不会一刀切地分配工作。",
    pitfallTips: "不要平均分配；不要总是给同样的人。核心：展示你了解每个人的特点因材施教。",
    starFramework: { situation: "需要分配任务的场景", task: "团队成员的不同特点", action: "如何根据不同特点分配", result: "任务完成的效果" },
    versions: { short: "因材施教。了解每个人的优势和意愿，分配匹配的任务而不是平均分配。关键节点跟踪进度但给足够的自主空间。",
      standard: "因材施教是最重要的原则。有人擅长执行就给他明确的目标和标准。有人需要成长就给更有挑战的任务。有人需要认可就分配能出彩的工作。关键节点跟踪进度但给足够自主空间。" },
    migrationTips: "如果没有正式经验，可以说在项目协作中的分工体会。" },
  { id: "leader-03", category: "领导力类", question: "团队成员不服你怎么办", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察领导力和处理人际关系的能力。面试官想知道你如何建立团队信任。",
    pitfallTips: "不要说不服我就让他服；不要说我用职位压人。核心：展示你用行动证明能力而不是用权力。",
    starFramework: { situation: "被挑战或不服的场景", task: "需要建立信任和权威", action: "用什么方式赢得认同", result: "团队关系的变化" },
    versions: { short: "先用行动证明能力而不是用职位压人。主动承担最难的任务搞定后自然会建立信任。同时1on1了解诉求对齐预期。",
      standard: "先用行动证明——主动承担最难的任务搞定后自然会建立信任。然后是沟通——1on1了解对方诉求对齐预期。最后是结果——做出的决策和分配让大家觉得公平公正。这三步走下来团队成员自然会认可你。" },
    migrationTips: "如果没经历过，可以说被说服的经历反过来理解。" },
  { id: "leader-04", category: "领导力类", question: "如何看待管理这件事", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察对管理岗位的理解是否成熟。面试官想知道你是想当官还是想做事。",
    pitfallTips: "不要管理就是管人。核心：好的管理=让团队做更好的自己+帮团队拿到结果。",
    starFramework: { situation: "观察到的好的和不好的管理", task: "心目中好的管理者画像", action: "自己尝试实践的管理原则", result: "效果如何" },
    versions: { short: "管理三个层次。第一层管事——目标分解进度跟进。第二层带人——发现优势帮成长。第三层建体系——建立可持续运转的流程。好管理者不是自己多厉害而是团队多厉害。",
      standard: "管理不是管人而是帮人拿结果。好的管理者做三件事：定方向告诉团队我们去哪为什么、清障碍把阻挡前进的问题一个个解决掉、给反馈让每个人知道自己做得好不好怎么改进。管理者的成功不是自己多厉害而是团队有多厉害。" },
    migrationTips: "如果没做过管理，把没有管理经验转化成在做管理的准备。" },
  { id: "leader-05", category: "领导力类", question: "如何激励团队成员", weight: "低", weightScore: 3, isPremium: true,
    interviewerWants: "考察领导力风格。面试官想知道你是否明白激励的本质是帮人找到意义和成就感。",
    pitfallTips: "不要说多发钱；不要说团建吃饭。核心：展示差异化激励——不同的人需要不同的激励方式。",
    starFramework: { situation: "一个需要激励的团队成员", task: "他当时的状态和需求", action: "做了什么事让他重新有动力", result: "状态变化和产出提升" },
    versions: { short: "差异化激励。有人需要成长给挑战，有人需要认可公开表扬，有人需要意义连接到公司战略。核心是知道每个人的驱动开关在哪。",
      standard: "激励不是统一方法。有人需要成长感——给他有挑战的任务帮他把成长显性化。有人需要认可感——公开表扬具体贡献。有人需要意义感——把日常工作和公司战略连接起来。核心是通过日常交流了解每个人的动力来源然后对症下药。" },
    migrationTips: "如果没带过人可以分享你被激励的经历反过来理解激励。" },
  { id: "industry-01", category: "行业深挖类", question: "怎么看待这个行业的发展趋势", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察行业视野和前瞻性思考。面试官想知道你是低头干活的人还是抬头看路的人。",
    pitfallTips: "不要说这个行业前景很好——太浅。核心：给出2-3个具体趋势+自己的判断。",
    starFramework: { situation: "对当前行业格局的理解", task: "未来最重要的三个趋势", action: "每个趋势背后的逻辑和影响", result: "如何为这些趋势做准备" },
    versions: { short: "三个趋势。垂直化——通用SaaS饱和后垂直行业深度方案更有壁垒。智能化——AI深度嵌入产品。服务化——产品差异化缩小后服务+效果变核心竞争力。",
      standard: "三大趋势。垂直深化——通用SaaS竞争激烈后垂直行业深度方案更有壁垒因为替换成本高。AI原生——不是加AI功能而是从底层用AI思维设计产品。效果付费——客户从买工具变成买效果商业模式会演化。" },
    migrationTips: "如果对行业不熟悉，展示你的研究过程和从研究中得出的初步判断。" },
  { id: "industry-02", category: "行业深挖类", question: "你怎么看待我们的竞争对手", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察竞争格局的理解深度。面试官想确认你是真的研究过还是面试前看了两眼。",
    pitfallTips: "不要说不了解竞品；不要说明显不对的竞品。核心：给出核心竞品+对比分析+你的判断。",
    starFramework: { situation: "基于对行业的调研", task: "分析贵公司主要竞争对手", action: "从产品定价客户三个维度做对比", result: "看到的贵公司差异化优势" },
    versions: { short: "分三类分析。直接竞品产品功能趋同但贵公司AI领先5%。大厂有流量但不够专注。AI原生创业公司最灵活而贵公司的护城河是行业数据的积累。",
      standard: "分三类竞品。直接竞品A/B公司——功能趋同但贵公司AI意图识别领先5%。潜在竞品大厂——有流量但客服只是功能模块不专注。未来竞品AI原生创业公司——最灵活但缺客户基础和行业理解。贵公司护城河在行业数据的积累。" },
    migrationTips: "如果了解有限，坦诚说并在说的范围内保证准确。" },
  { id: "industry-03", category: "行业深挖类", question: "AI对这个行业的影响", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察行业视野和对新技术的敏感度。面试官想知道你是焦虑还是拥抱变化。",
    pitfallTips: "不要AI会取代很多工作这种笼统说法。核心：展示你关注了AI的影响+有自己的判断+知道怎么应对。",
    starFramework: { situation: "对AI在行业应用现状的了解", task: "AI对运营领域的具体影响", action: "为了适应变化做的准备", result: "对未来的判断" },
    versions: { short: "效率革命不是替代危机。重复性工作被AI替代后客户成功经理可更专注深度沟通。但信任和共情是AI替代不了的。",
      standard: "AI带来的是效率革命不是替代危机。重复性工作被替代后人可以做更有价值的事。但客户关系管理的核心是信任和共情这是AI做不到的。我主动在学习AI工具让自己从做重复工作的人变成用AI放大能力的人。" },
    migrationTips: "如果对AI不了解，诚实说在补这块知识并展示学习行动。" },
  { id: "industry-04", category: "行业深挖类", question: "未来3年发展趋势", weight: "中", weightScore: 5, isPremium: true,
    interviewerWants: "考察行业视野和前瞻性思考能力。",
    pitfallTips: "不要说了一大堆宏观趋势没自己的判断。核心：具体趋势+自己的判断+对自己的意义。",
    starFramework: { situation: "对当前行业格局的理解", task: "未来最重要的三个趋势", action: "每个趋势背后的逻辑", result: "为这些趋势做了什么准备" },
    versions: { short: "三个趋势：从功能竞争到效果竞争、从水平SaaS到垂直SaaS、从人适应软件到软件适应人。这对我意味着深耕行业理解、掌握AI工具、建立效果思维。",
      standard: "从功能竞争到效果竞争——产品功能趋同后谁能帮客户更快出效果谁赢。从水平SaaS到垂直SaaS——通用竞争饱和垂直行业深度方案有更高替换成本。从人适应软件到软件适应人——AI让交互方式改变客户成功职责也会变化。" },
    migrationTips: "分享你的思考过程本身就有价值哪怕判断不完全准确。" },
  { id: "industry-05", category: "行业深挖类", question: "最近在读什么书", weight: "低", weightScore: 3, isPremium: true,
    interviewerWants: "考察学习习惯和输入质量。面试官想知道你在工作之外有没有持续学习。",
    pitfallTips: "不要说最近没看书——等于没有学习习惯。核心：说1-2本对工作有启发的书+具体启发点。",
    starFramework: { situation: "什么背景下选择了这本书", task: "这本书主要讲了什么", action: "哪些观点特别有启发", result: "把这些启发用到了哪里" },
    versions: { short: "最近在读《销售加速公式》——讲SaaS公司如何用数据和流程驱动增长。书里把经验流程化的理念特别启发我。",
      standard: "最近在读《销售加速公式》。书里核心观点是SaaS增长靠可复用的系统而不是几个天才销售。其中一个概念Deal Desk机制启发我在团队推了客户红线预警机制，响应速度从8小时缩到2小时。" },
    migrationTips: "如果最近没看书，可以说听行业播客或公众号，诚实展示学习习惯。" },];
if (typeof window !== 'undefined') { window.QUESTIONS = QUESTIONS; }
// ===== 工具函数 =====
function getQuestionsByCategory(cat) { for (var i=0,res=[]; i<QUESTIONS.length; i++) { if (QUESTIONS[i].category===cat) res.push(QUESTIONS[i]); } return res; }
function getCategories() { var cats=[]; for (var i=0; i<QUESTIONS.length; i++) { if (cats.indexOf(QUESTIONS[i].category)===-1) cats.push(QUESTIONS[i].category); } return cats; }
function getQuestionById(id) { for (var i=0; i<QUESTIONS.length; i++) { if (QUESTIONS[i].id===id) return QUESTIONS[i]; } return null; }
function getFreeQuestions() { for (var i=0,res=[]; i<QUESTIONS.length; i++) { if (!QUESTIONS[i].isPremium) res.push(QUESTIONS[i]); } return res; }
function getPremiumQuestions() { for (var i=0,res=[]; i<QUESTIONS.length; i++) { if (QUESTIONS[i].isPremium) res.push(QUESTIONS[i]); } return res; }
function searchQuestions(kw) { kw=kw.toLowerCase(); var res=[]; for (var i=0; i<QUESTIONS.length; i++) { var q=QUESTIONS[i]; if (q.question.toLowerCase().indexOf(kw)!==-1||q.category.toLowerCase().indexOf(kw)!==-1) res.push(q); } return res; }
function getCategoryStats() { var s={}; for (var i=0; i<QUESTIONS.length; i++) { var q=QUESTIONS[i]; if (!s[q.category]) s[q.category]={total:0,free:0,premium:0}; s[q.category].total++; if (q.isPremium) s[q.category].premium++; else s[q.category].free++; } return s; }